### ISSUE TITLE
Update the minimum requirement for CMake to 3.8.2

### ISSUE THREAD

**Issue by allsey87** [ilpincy/argos3#115]
The introduction of the `$<IF:...>` generator statements in commit 1bf398cde0ccfd6b7cc17afbb0fd1bc2feb2ba11 breaks cmake configuration/generation for CMake versions < 3.8.2.

The minimum required version for CMake defined in [CMakeLists.txt:4](https://github.com/ilpincy/argos3/blob/3.0.0-beta55/src/CMakeLists.txt#L4) should be updated to reflect this.

**Comment by ilpincy** [comment]
I think I'll remove the generators. They're not the right approach for this problem. This will also make ARGoS easier to compile in older systems.
