### ISSUE TITLE
Qt-OpenGL changing color affects other objects

### ISSUE THREAD

**Issue by jtrautmann** [ilpincy/argos3#126]
I added my own class which inherits from `CQTOpenGLUserFunctions` and has a registered user function `void Draw(CFootBotEntity& c_entity)`. This function calls `DrawRay`, using the color green. In principle this works, but there is one problem: this leads to the ground also being drawn in green. My guess is that the function `DrawRay` changes the color internally and that it doesn't get changed back. My first thought was that I could maybe change it back using the `SetColor` function, but then I realized there is no function which would give me the current color, so this doesn't seem to be possible.

I built argos using the current state of the master.
OS: Ubuntu 18.04

**Comment by allsey87** [comment]
I guess you (via DrawRay) are changing the global color with the `glColor` function, in which case you should take the current OpenGL color and restore it once you are done. I think this can be done with `glGet` with argument `GL_CURRENT_COLOR` or `glGet` with argument `GL_RGBA_MODE`.

**Comment by jtrautmann** [comment]
Thank you for your answer. I tried this and it works:

```
float currentColor[4];
glGetFloatv(GL_CURRENT_COLOR,currentColor);
DrawRay(ray, CColor::GREEN);
glColor3ub(currentColor[0],currentColor[1],currentColor[2]);
```

But as you said, this is a bit of a hack. Of course I could duplicate the from `DrawRay`, but duplicate code is never a good solution. And when would it ever make sense to use the function `DrawRay` then? Maybe there is a logic behind this, but I don't really see it. In my eyes, it makes far more sense to reset the color at the end of the `DrawRay` method.

**Comment by ilpincy** [comment]
This should not happen. I'll check it later today.

**Comment by jtrautmann** [comment]
I noticed this also happens when selecting a robot: the ground also gets white like the selection box.

**Comment by jtrautmann** [comment]
I don't know exactly when this was fixed, but it seems the problem doesn't occur anymore.
