### ISSUE TITLE
Black area and no GUI icons

### ISSUE THREAD

**Issue by pawel-jakubowski** [ilpincy/argos3#14]
Hi,

I compiled simulator under Ubuntu 15.10 64-bit and I get black floor in simulation. What is more there is no icons for controls. Is there any way to fix it (maybe I forgot to set some variable during compilation?).

It looks like this:
![argos_problem](https://cloud.githubusercontent.com/assets/9104400/11458682/48dba25a-96c5-11e5-98d5-14ad775bdc3f.png)

**Comment by ilpincy** [comment]
You probably have the wrong paths in $HOME/.config/Iridia-ULB/ARGoS.conf (see also https://github.com/ilpincy/argos3#running-the-argos-simulator). Either fix the paths (/usr/local instead of /usr, I imagine), or simply erase the file and ARGoS will create a new one automatically.

**Comment by pawel-jakubowski** [comment]
That was it, thanks!
