### ISSUE TITLE
Garbled Spiri model

### ISSUE THREAD

**Issue by ilpincy** [ilpincy/argos3#156]
The Spiri model uses `CQTOpenGLObjModel`. Before beta57, it worked perfectly. Since beta57, it looks garbled (see screenshot):

<img width="932" alt="Screen Shot 2021-02-16 at 11 57 21" src="https://user-images.githubusercontent.com/2726243/108095684-237bad80-704e-11eb-9524-fe2ce8b50647.png">

I have spent some time trying to fix this issue, but I can't seem to find the problem. `GLError()` returns no error anywhere.

With the other robots the visualization works as intended.

**Comment by allsey87** [comment]
I'll look into it by the end of the week and get back to you with either an updated model or a bug fix :)

**Comment by ilpincy** [comment]
Thank you! Very appreciated! :-)

**Comment by allsey87** [comment]
@mk-heinrich would you have time to look into this with me tomorrow? I guess we just need to reexport the Spiri model with the same settings as used by the other robots

**Comment by allsey87** [comment]
Commit b98187cf04a1d431daf68fabdccb270e0193f79b is to blame. It changes part of the code to use GLdouble leaving the just unchanged. I remember looking at this PR and thinking that it looks like a very quick find-and-replace-all job with little testing... I hope it hasn't introduced errors into other parts of the code...
