### ISSUE TITLE
QT OpenGL user functions for DrawTriangle, DrawPolygon, and DrawCircle do not respond to b_fill = false

### ISSUE THREAD

**Issue by alanmillard** [ilpincy/argos3#16]
Source file: argos3/src/plugins/simulator/visualizations/qt-opengl/qtopengl_user_functions.cpp

GL_LINE should be used instead of GL_LINES in the following code:

glPolygonMode(GL_FRONT_AND_BACK, b_fill ? GL_FILL : GL_LINES);

**Comment by ilpincy** [comment]
Thanks Alan! :-)
