### ISSUE TITLE
Default e-puck does not move in 3D

### ISSUE THREAD

**Issue by jharwell** [ilpincy/argos3#163]
I tried the e-puck that comes with ARGoS with the dynamics3D model, and the robot appears not to move even though I set the wheel speeds. I checked via some debug print statements that the left/right bullet "motors" are being set correctly from the wheel velocities in the UpdateFromEntityStatus() function. In fact, the robot IS moving but so slowly that even after 1000s of timesteps the entity anchor position has not changed to 4 decimal places. If I multiply the set wheel speed by 10 for left and right, then the robot does move, but it is still verrrryyyyy slow. The exact same settings with the foot-bot (without the 10x factor) cause it to move noticeably.

What is going on here ?

@allsey87 this might be a question for you, because it involves the 3D physics engine.

**Comment by ilpincy** [comment]
Without looking at the code, this looks like a calibration problem (assuming the code is correct, which I assume it is).

**Comment by allsey87** [comment]
Indeed, it needs to be calibrated so the dynamics3d model roughly matches the dynamics2d model. I was suggesting in #146 that @karthiks1701 have a go at fixing this in return for resolving ilpincy/argos3-kheperaiv#6 and adding a dynamics3d model for the Khepera IV.

**Comment by allsey87** [comment]
Let use issue #165 for resolving this.
