### ISSUE TITLE
How to overcome "Lua53Config.cmake  /   lua53-config.cmake" directory issue..?

### ISSUE THREAD

**Issue by kashif-hub** [ilpincy/argos3#172]
How to overcome the issue related to the installation of the ARGoS module and cmake .. command results some error related to "Lua53Config.cmake / lua53-config.cmake" which is shoen in snapshot..?
![image](https://user-images.githubusercontent.com/84039991/117882598-f0029500-b2c3-11eb-83f6-9ef46eeb08e0.png)

**Comment by ilpincy** [comment]
This is not an issue with the ARGoS core, but with the module code. They have a misconfigured `CMakeLists.txt`. Please submit an issue with their repository.

**Comment by ilpincy** [comment]
I don't know - please refer to the people who made that code. Again, this is not the space to ask for coding advice. This is a space to report issues with the ARGoS core.
