### ISSUE TITLE
HOw to overcome the issue in module code of repository "CMakeList.txt"..?

### ISSUE THREAD

**Issue by kashif-hub** [ilpincy/argos3#173]
How to overcome the issue in the module code misconfiguration and getting results related to "Lua53Config.cmake" as shown in snapshot..?
![image](https://user-images.githubusercontent.com/84039991/117885410-44f3da80-b2c7-11eb-99f3-7375426d5331.png)

**Comment by ilpincy** [comment]
You have already submitted an identical issue and I have already replied. Please refer to the repository that is offering that code. This is not an issue with the ARGoS core.
