### ISSUE TITLE
No package 'argos3_simulator' found

### ISSUE THREAD

**Issue by kashif-hub** [ilpincy/argos3#179]
cmake ../src
-- Checking for module 'argos3_simulator'
--   No package 'argos3_simulator' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  cmake/ARGoSBuildChecks.cmake:6 (pkg_check_modules)
  CMakeLists.txt:31 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ffmpeg/software/argos3-epuck/build/CMakeFiles/CMakeOutput.log".
![image](https://user-images.githubusercontent.com/84039991/124942147-ceecc500-e024-11eb-81d8-aedb5d3ea759.png)

**Comment by allsey87** [comment]
Could you provide a link to the version of the e-puck plugin that you are trying to compile?

**Comment by ilpincy** [comment]
This should not be here, it's an issue with the e-puck plugin. I'll mark it as invalid and close it.
