### ISSUE TITLE
gl.h not found in Mac OSX 11.4 Big Sur

### ISSUE THREAD

**Issue by vito-trianni** [ilpincy/argos3#191]
The following error is returned when compiling from sources:
[ 64%] Building CXX object plugins/robots/block/CMakeFiles/argos3plugin_simulator_block.dir/simulator/qtopengl_block.cpp.o
In file included from /Users/vtrianni/Work/argos3/src/plugins/robots/block/simulator/qtopengl_block.cpp:7:
/Users/vtrianni/Work/argos3/src/plugins/robots/block/simulator/qtopengl_block.h:16:10: fatal error: 'gl.h' file not found

However, the OpenGL framework was correctly detected by cmake (see the output below), and always checking with ccmake confirms that the include directories are correctly included.

Here's the output of cmake:
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found DLFCN: /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/lib/libdl.tbd  
-- Found Pthreads: /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/lib/libpthread.tbd  
-- Found FreeImage: 
-- Could NOT find GooglePerfTools (missing: GOOGLEPERFTOOLS_LIBRARY GOOGLEPERFTOOLS_INCLUDE_DIR) 
-- Found Doxygen: /opt/homebrew/bin/doxygen (found version "1.9.2") found components: doxygen dot 
-- Found ASCIIDoc: /opt/homebrew/bin/asciidoc  
-- Found OpenGL: /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework   
-- Found GLUT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/GLUT.framework  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found Qt6: version 6.2.1
-- Found Qt6Widgets: version 6.2.1
-- Found Qt6Gui: version 6.2.1
-- Found Qt6OpenGLWidgets: version 6.2.1
-- Found Lua: /opt/homebrew/lib/liblua5.4.dylib (found version "5.4.3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vtrianni/Work/argos3/build_simulator

**Comment by allsey87** [comment]
Hi Vito, I'll have a quick look
