### ISSUE TITLE
Not using threads on WSL2 (Windows 11)

### ISSUE THREAD

**Issue by pepsiman3** [ilpincy/argos3#214]
I'm getting a message "not using threads" on my WSL2 Ubuntu distro, even though I have it set to use multiple virtual cores, is this a known issue / is it normal?

**Comment by allsey87** [comment]
What is the value of the `threads` attribute under `framework/system`? Perhaps it is something like this:
```xml
<framework>
    <system threads="0" />
    <experiment length="0" ticks_per_second="10" random_seed="0" />
  </framework>
```

**Comment by pepsiman3** [comment]
That worked, thank you
