### ISSUE TITLE
argos visualization error when running CPFA: cannot find CPFA_qt_user_functions on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by sivaavala** [ilpincy/argos3#220]
**Hi, When I try to run the CPFAExample.xml experiment with visualization, I get the following error:**

[INFO] The physics engine "dyn2d" will perform 10 iterations per tick (dt = 0.00625 sec)
[FATAL] Failed to initialize the visualization. Parse error in the <visualization> subtree.
[FATAL] Failed opening QTOpenGL user function library
[FATAL] Symbol "CPFA_qt_user_functions" not found

**My build gets created from the following compilation. I made the following changes to CMakeLists.txt, which is attached. Could you please help me debug the issue?**

Deleting and recreating the build directory 
Configuring Makefiles with CMAKE...
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ARGoS: /usr/lib/argos3/libargos3core_simulator.so
-- Found DLFCN: /usr/lib/x86_64-linux-gnu/libdl.a  
-- Found Pthreads: /usr/lib/x86_64-linux-gnu/libpthread.a  
-- Found FreeImage: 
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindOpenGL.cmake:315 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  /usr/share/argos3/cmake/FindARGoSQTOpenGL.cmake:21 (find_package)
  /usr/share/argos3/cmake/ARGoSConfig.cmake:131 (find_package)
  CMakeLists.txt:47 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'glut'
--   No package 'glut' found
-- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found Qt6: version 6.2.4
-- Found Qt6Widgets: version 6.2.4
-- Found Qt6Gui: version 6.2.4
-- Found Qt6OpenGLWidgets: version 6.2.4
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.3.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.3.6") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/siva/argos/CPFA-ARGoS/build
Making...

[CMakeLists.txt](https://github.com/ilpincy/argos3/files/11302425/CMakeLists.txt)

**Thanks in advance!**

**Comment by ilpincy** [comment]
Please contact the authors of the CPFA code. This is not an issue with the ARGoS core.
