### ISSUE TITLE
Camera angled at 90 degrees

### ISSUE THREAD

**Issue by rubenvereecken** [ilpincy/argos3#25]
Strangely, a custom-defined camera is angled at 90 degrees using the following specific setting:

`        <placement idx="1" position="0,-5, 1" look_at="0,0,0" lens_focal_length="20" />`

as can be seen on this image:

![](https://sc-cdn.scaleengine.net/i/2326818a1e31323ea3ab2b46bf3aee91.png)

I can fix it by having a non-zero `x` position, like so:

`        <placement idx="1" position="0.00001,-5, 1" look_at="0,0,0" lens_focal_length="20" />`

**Comment by ilpincy** [comment]
Thanks for the bug report! At the end of the week I'll work on this. I'll
add the possibility to specify the Up vector of the camera manually, for
situations in which the automatic calculation is ambiguous (like this one).

Cheers,
Carlo

On Wed, May 25, 2016 at 10:49 AM, Ruben Vereecken <notifications@github.com>
wrote:

> Strangely, a custom-defined camera is angled at 90 degrees using the
> following specific setting:
>
> <placement idx="1" position="0,-5, 1" look_at="0,0,0"
> lens_focal_length="20" />
>
> as can be seen on this image:
>
>
> <https://camo.githubusercontent.com/eea987ac6d5390d74d13ff931a8c5a26ee5801bb/68747470733a2f2f73632d63646e2e7363616c65656e67696e652e6e65742f692f32333236383138613165333133323365613361623262343662663361656539312e706e67>
>
> I can fix it by having a non-zero x position, like so:
>
> <placement idx="1" position="0.00001,-5, 1" look_at="0,0,0"
> lens_focal_length="20" />
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ilpincy/argos3/issues/25>
>



-- 
Carlo Pinciroli, Ph.D.
http://carlo.pinciroli.net/

**Comment by rubenvereecken** [comment]
Great! Thanks for taking a look so swiftly.
