### ISSUE TITLE
robots able to comunicate through obstacles via RAB

### ISSUE THREAD

**Issue by James-SW** [ilpincy/argos3#32]
Footbots are able to occasionally communicate through obstacles using the RAB sensor and actuator.

Adding CCI_RangeAndBearingActuator and CCI_RangeAndBearingSensor to footbot_diffusion.cpp and setting 'show_rays="true"' in diffusion_10.argos will reproduce the bug as shown below.  

![screenshot from 2017-02-01 12-48-02](https://cloud.githubusercontent.com/assets/22681030/22507519/daf5a892-e87d-11e6-8957-6afd4bd9ab32.png)

This was also tested with two footbots either side of a wall. They would continue to occasionally connect with one another through the object.

**Comment by ilpincy** [comment]
Thanks for spotting this! I'll look into it next (porting to Qt 5 took more time than anticipated)
