### ISSUE TITLE
Draw Position Error After Drawing Circles

### ISSUE THREAD

**Issue by Gusz92** [ilpincy/argos3#37]
Hello,

The function of  `CQTOpenGLUserFunctions::DrawCircle( ) `did not do the job `glPushMatrix();` and  `glPopMatrix();` So things drawed after the first call of this function will be distracted. I tried add them to this function, seems solve this problem.

Cheers,
Guangsha Xu

**Comment by ilpincy** [comment]
Hello Gusz92, Can you make a pull request with the change you made? Thanks! :-)

**Comment by cardinot** [comment]
just for reference... fixed here:
https://github.com/ilpincy/argos3/commit/9c208c4d6986c05aba1b9041921afd7e99d39b2c
