### ISSUE TITLE
Unimplemented functions

### ISSUE THREAD

**Issue by allsey87** [ilpincy/argos3#41]
The following function prototypes are not implemented and never called.

https://github.com/ilpincy/argos3/blob/3.0.0-beta46/src/plugins/simulator/entities/led_equipped_entity.h#L56
https://github.com/ilpincy/argos3/blob/3.0.0-beta46/src/plugins/simulator/entities/led_equipped_entity.h#L57

**Comment by ilpincy** [comment]
Their implementation is here:

https://github.com/ilpincy/argos3/blob/3.0.0-beta46/src/plugins/simulator/entities/led_equipped_entity.cpp#L108

and here:

https://github.com/ilpincy/argos3/blob/3.0.0-beta46/src/plugins/simulator/entities/led_equipped_entity.cpp#L118

**Comment by allsey87** [comment]
Look again. Those methods are inside the SActuator struct and are not implemented.

**Comment by ilpincy** [comment]
Oh, I see - you're right! They're a remnant of my implementation of `CLEDEquippedEntity::Enable()` and `CLEDEquippedEntity::Disable()`. The unimplemented methods can be safely removed.
