### ISSUE TITLE
A Sample e-Puck Experiment

### ISSUE THREAD

**Issue by Mbt925** [ilpincy/argos3#44]
ARGoS has a set of footbot experiments. Is there any sample for e-puck?

**Comment by ilpincy** [comment]
Yes, just look in the experiments folder.

Please write in the forum for this kind of questions, the issue tracker is for issues with the code.

**Comment by Mbt925** [comment]
My bad. I want to reimplement the "footbot_foraging" sample to use e-puck instead of foot-bot.
Why there is no specific sensor implementation for e-puck? Should I use the generic sensors implementation?
I want to use the extended e-puck ground sensors too. Is it possible in ARGoS?

Thank you.
