### ISSUE TITLE
E-Puck Sensors Implementation

### ISSUE THREAD

**Issue by Mbt925** [ilpincy/argos3#46]
I want to reimplement the "footbot_foraging" sample to use e-puck instead of foot-bot.
Why there is no specific sensor implementation for e-puck? Should I use the generic sensors implementation?
I want to use the extended e-puck ground sensors too. Is it possible in ARGoS?

Thank you.

**Comment by ilpincy** [comment]
Please refrain from asking these questions here. Use the forum instead. The issue tracker is only for bugs.

**Comment by Mbt925** [comment]
I am sorry. It was by mistake. I could not delete the issue after.
