### ISSUE TITLE
Segfault when accessing gripped entity

### ISSUE THREAD

**Issue by randUsr** [ilpincy/argos3#56]
I get a Segemantation fault, when accessing the `EmbodiedEntity` the gripper holds via the `.GetGrippedEntity()` function.
I forked the argos3-examples repository and implemented a loopfunction, that produces the segault with the gripper example.

Steps to reproduce:
1. clone https://github.com/randusr/argos3-examples
1. build & run gripper example
1. press start in gui
1. as soon as the robot grips the cylinder, the Segfault occurs

**Comment by ilpincy** [comment]
Thanks for the bugreport! I'll have a look at it in the weekend.

**Comment by ilpincy** [comment]
[fix.txt](https://github.com/ilpincy/argos3/files/1671821/fix.txt)
It's a bug in your code. Here the fix. I suggest you to learn how references work in C++, because the bug you had was due to that.

**Comment by randUsr** [comment]
Thanks for looking through the code and the fix.
Sorry for bothering you with trivialities!
