### ISSUE TITLE
FootBot LEDs only support colors with 0 or 255, all other colors just show up as white.

### ISSUE THREAD

**Issue by PeterMitrano** [ilpincy/argos3#72]
for example, `m_pcLEDs->SetAllColors(CColor::PURPLE);`, will just show up as white.

**Comment by ilpincy** [comment]
Uhm, weird - I'll look into it tomorrow...

**Comment by PeterMitrano** [comment]
I'd be happy to fix this but after digging through the code I can't figure out where the bug is--do you have any hunches?

**Comment by ilpincy** [comment]
The color is set [here](https://github.com/ilpincy/argos3/blob/master/src/plugins/robots/foot-bot/simulator/qtopengl_footbot.cpp#L362), and apparently the values I'm setting for `pfEmission` are way out of scale, hence the white. Setting `fEmissionFactor = 1.0` solves the problem.
