### ISSUE TITLE
How / where to free up data for plug-ins using CFactory

### ISSUE THREAD

**Issue by allsey87** [ilpincy/argos3#78]
The following specializations of CFactory are created via macros but are never destroyed. This leads to memory errors being reported by Valgrind. We need to call these functions somewhere:

1. `CFactory<CDynamics3DPlugin>::Destroy()`
2. `CFactory<CCameraSensorSimulatedAlgorithm>::Destroy()`
3. `CFactory<CBatteryDischargeModel>::Destroy()`

**Comment by ilpincy** [comment]
It's not really a problem - those are not real leaks. The memory gets cleaned up anyway when the process is closed, either when ARGoS is used as a standalone program, or when ARGoS is used as a library attached to other software.

**Comment by allsey87** [comment]
Not a problem then :)
