### ISSUE TITLE
Cannot add light entities from the loop functions, unless a light is already in the XML

### ISSUE THREAD

**Issue by LPitonakova** [ilpincy/argos3#80]
ARGoS crashes when a footbot with colored_blob_omnidirectional_camera is in the scene but no light or LED has been added. I believe the correct behaviour should be the blob camera simply returning an empty readings array.

Relevant argos file parts:

```
<controllers>
<baseRobot id="baseRobot" library="build/controllers/libbaseRobot.so">
      <actuators>
        <differential_steering implementation="default" />
        <leds implementation="default" medium="leds" />
      </actuators>
      <sensors>
        <footbot_proximity implementation="default" show_rays="false" />
        <footbot_light implementation="rot_z_only" show_rays="true" />
        <footbot_motor_ground implementation="rot_z_only" />
        <colored_blob_omnidirectional_camera implementation="rot_z_only" medium="leds" show_rays="true" noise_std_dev="0" />
      </sensors>
    </baseRobot>
</controllers>

<arena size="5, 5, 2" center="0,0,1">
	
       <floor id="floor"
           source="loop_functions"
           pixels_per_meter="100" />

      <foot-bot id="robot0">
        <body position="-1,0,0" orientation="90,0,0" />
        <controller config="baseRobot"/>
      </foot-bot>

      <!--
     <light id="light_1"
           position="0,0,1.0"
           orientation="0,0,0"
           color="yellow"
           intensity="0.0"
           medium="leds" />
    -->
</arena>
```

**Comment by allsey87** [comment]
There are lots of different types of crashes. Do you mean a segfault perhaps?

Can you generate a GDB backtrace for us?

**Comment by LPitonakova** [comment]
`[FATAL] Entity map for type "light" not found.`

**Comment by allsey87** [comment]
@ilpincy the exception is thrown from: https://github.com/ilpincy/argos3/blob/master/src/core/simulator/space/space.cpp#L114

At a guess "light" is not being added to [`m_mapEntitiesPerTypePerId`](https://github.com/ilpincy/argos3/blob/master/src/core/simulator/space/space.h#L277). Perhaps there is something wrong with the `REGISTER_STANDARD_SPACE_OPERATIONS_ON_ENTITY` macro? It seems ok to me.

**Comment by LPitonakova** [comment]
My guess is that you simply need to catch the entity doesn't exist exception when the blob sensor asks for all light entities and finds nothing.

**Comment by allsey87** [comment]
You are right: I didn't notice that you had "light_1" commented out in your XML. It happens during an [update of the footbot_light sensor](https://github.com/ilpincy/argos3/blob/master/src/plugins/robots/foot-bot/simulator/footbot_light_rotzonly_sensor.cpp#L121).

**Comment by LPitonakova** [comment]
I'm not sure.. there is an assumption that a light or an LED won't be added programatically later. Also, adding / removing light from an argos file would be much easier if you could just comment out the light and didn't have to touch the robot xml declaration.

But of course, that's your call Carlo.

**Comment by ilpincy** [comment]
I have never encountered a case in which people wanted to add lights in the loop functions, so far. You make a good point - if that's how you intend to add lights, then the current behavior is wrong.

BTW, the title of this issue is wrong - cameras and LEDs have nothing to do with it.

**Comment by allsey87** [comment]
> This is correct behavior. ARGoS is informing you that you have a light sensor that would do nothing.

While I agree with this, the error message is so uninformative I would almost consider it a bug.

**Comment by ilpincy** [comment]
I found out that there was an inconsistency between the generic light sensor and the foot-bot light sensor. The generic light sensor did not bomb out if no light is in the environment, while the foot-bot one did. In ee1ad8df72efbc6adebb5a4262ddf51b249ea36d, I made it so the foot-bot one behaves the same as the generic one. This solves the issue.

**Comment by LPitonakova** [comment]
@ilpincy I have argos installed via homebrew, is there a way of testing this without having to compile from source and link argos globally? What I was after basically is for argos to not stop the simulation when no light is found and a blob camera is attached to the robot. From the code change, it seems like that's what will happen now.

**Comment by ilpincy** [comment]
> no light is found and a blob camera is attached to the robot

The problem was that you had a foot-bot light sensor in your XML file, and no light added to the arena. The change I made fixes this issue.

If you want to try the latest ARGoS using homebrew, just type

    $ brew install --HEAD argos3

**Comment by LPitonakova** [comment]
yes, that's it. thanks!

**Comment by ilpincy** [comment]
Does that mean it works for you?

**Comment by LPitonakova** [comment]
sorry, yes :)

**Comment by ilpincy** [comment]
OK great - I'll make a new release now.
