### ISSUE TITLE
Error initialising controllers

### ISSUE THREAD

**Issue by manooshsamiei76** [ilpincy/argos3#85]
whenever I want to run any of argos3 experiments I encounter the error of initializing controllers.
I attached the picture of what I write and what I get in the terminal. can anyone help me with this problem, please?

![image](https://user-images.githubusercontent.com/36368861/44946861-4895ea80-ae19-11e8-9e25-2158736ff321.png)

**Comment by ilpincy** [comment]
Have you checked that the files mentioned in the error message exist?

**Comment by manooshsamiei76** [comment]
yes, I checked. They do not exist and this is my problem!
I found the footbot_diffusion library and placed it manually in an artificial directory that I made. Now it runs but with lots of warnings and errors. Do you know why I do not have any folder named Build?

**Comment by manooshsamiei76** [comment]
oh, thank you very much! problem solved.
