### ISSUE TITLE
How to make the code run repeatedly in the simulation platform?

### ISSUE THREAD

**Issue by Hi-Ryan** [ilpincy/argos3#87]
I want to run the same code file many times to get experimental data. How can I get the simulation platform to finish the experiment and start the next cycle immediately? And you don't need to update the 'random_seed' variable of the. argos file manually anymore.

Can you give me some good advice? I spent too much time in my lab setting 'random_seed' manually.

**Comment by allsey87** [comment]
Setting random_seed to zero should give you a random seed every time you run your experiment. If you are at the stage of collecting data, the general workflow would be to turn off the visualization and to call ARGoS in a bash loop. Your data can be collected using a loop function.

Please note that the Github is for development issues only. Please post questions like this to the forum in the future: https://www.argos-sim.info/forum/
