### ISSUE TITLE
Enhancement: Better diagnostics for physics engine transfer failures

### ISSUE THREAD

**Issue by jharwell** [ilpincy/argos3#91]
As I have been debugging why entity transfers between engines keeps failing, I added unique exception messages for each of the conditions that can cause a transfer failure, to help me and potentially others.

 I don't seem to be able to push my branch and open a pull request though--how can I do that? Do I need to fork the repo?

**Comment by ilpincy** [comment]
Thank you! Yes, you need to fork the repo, commit/push to your repo, and then submit a push request.
