### ISSUE TITLE
Margin for detecting gimbal lock in CQuaternion::ToEulerAngles is too large

### ISSUE THREAD

**Issue by allsey87** [ilpincy/argos3#93]
The [thresholds for detecting gimbal lock](https://github.com/ilpincy/argos3/blob/3.0.0-beta53/src/core/utility/math/quaternion.h#L189) are quite large and causing glitching it the QtOpenGL visualization. Changing these thresholds from 0.499 to 0.4999 almost eliminates this issue. Is there any reason not to change these values from 0.499 to either 0.4999 or 0.49999?

![a9boi](https://user-images.githubusercontent.com/3796345/56132825-412be780-5f8b-11e9-8797-e7b31d6c6e9d.gif)

**Comment by ilpincy** [comment]
> Is there any reason not to change these values from 0.499 to either 0.4999 or 0.49999?

No, feel free to set it to the value that is most appropriate for your simulations to be stable.

**Comment by allsey87** [comment]
Ok. I'll push a fix tomorrow changing the value to: 0.49999

**Comment by ilpincy** [comment]
Fine for me!
